development:
  clients:
    default:
      database: evil_hamster_development
      hosts:
        - localhost:27017
      options:
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: evil_hamster_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: primary
        max_pool_size: 1
        raise_not_found_error: false

production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
