# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6fea6bd29a4c94c81c4fcb2143b3fb897565f092dfeea90744effe7266d774764aeb7ca45d391753c085e2f30edd36fc50970e2b77796f6f93613b794fe8786

test:
  secret_key_base: 4de94cb95032a21a75805fe72e97d740ad83c98d03ea687bbbb91d5894d61e575e78c7de08cd92abe68e45bc57d6342d40a90fad1f46e23fbcd8ef7be3bd08cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
